server:
  port: 8080


spring:
  application:
    name: travelapp
  datasource:
    url: jdbc:mysql://localhost:3306/travelapp
    username: root
    password: Douglas@123
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
